name: custom_showcase
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 0.0.1
homepage: https://github.com/koorosh-k98/custom_showcase
issue_tracker: https://github.com/koorosh-k98/custom_showcase/issues

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
